# Generated by Django 5.1.2 on 2024-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
