# Generated by Django 5.1.2 on 2024-11-25 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('calle', models.CharField(blank=True, max_length=30)),
                ('numero', models.IntegerField()),
                ('localidad', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='OtrosDestinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('calle', models.CharField(blank=True, max_length=30)),
                ('numero', models.IntegerField()),
                ('localidad', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
        ),
    ]
