# Generated by Django 5.1.2 on 2024-11-25 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
        ('nodos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosdestinos',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estados.estado'),
        ),
    ]
