# Generated by Django 5.1.2 on 2024-11-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
        ('nodos', '0003_nodos_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nodos',
            new_name='Destino',
        ),
        migrations.RenameModel(
            old_name='OtrosDestinos',
            new_name='Nodo',
        ),
    ]
