# Generated by Django 5.1.2 on 2024-12-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0004_rename_nodos_destino_rename_otrosdestinos_nodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='calle',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='nodo',
            name='localidad',
            field=models.CharField(max_length=30),
        ),
    ]
