# Generated by Django 4.2 on 2024-12-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0005_alter_nodo_calle_alter_nodo_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='mapa',
            field=models.ImageField(blank=True, null=True, upload_to='mapa/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='mapa',
            field=models.ImageField(blank=True, null=True, upload_to='mapa/%Y/%m/%d'),
        ),
    ]
