# Generated by Django 4.2 on 2024-12-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0007_nodo_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='maps',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
