# Generated by Django 4.2 on 2024-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0008_alter_nodo_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='mapa',
        ),
        migrations.RemoveField(
            model_name='nodo',
            name='mapa',
        ),
        migrations.AddField(
            model_name='destino',
            name='maps',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
