# Generated by Django 5.1.2 on 2024-11-27 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estados', '0001_initial'),
        ('hojaderuta', '0003_alter_envio_hora_and_more'),
        ('nodos', '0004_rename_nodos_destino_rename_otrosdestinos_nodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpresoraNodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estados.estado')),
                ('nodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodos.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='ColaDeImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estados.estado')),
                ('trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hojaderuta.envio')),
                ('impresora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impresoras.impresoranodo')),
            ],
        ),
    ]
