# Generated by Django 5.1.2 on 2024-11-27 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('impresoras', '0001_initial'),
        ('nodos', '0004_rename_nodos_destino_rename_otrosdestinos_nodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reparto', models.BooleanField(default=False)),
                ('impresora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impresoras.impresoranodo')),
                ('nodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodos.nodo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
