# Generated by Django 4.2 on 2025-02-02 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodos', '0009_remove_destino_mapa_remove_nodo_mapa_destino_maps'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nodo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nodos',
            field=models.ManyToManyField(blank=True, null=True, to='nodos.nodo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
