# Generated by Django 4.2 on 2025-02-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0009_remove_destino_mapa_remove_nodo_mapa_destino_maps'),
        ('perfiles', '0002_remove_perfil_nodo_perfil_nodos_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nodos',
            field=models.ManyToManyField(blank=True, to='nodos.nodo'),
        ),
    ]
