# Generated by Django 4.2 on 2025-02-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0009_remove_destino_mapa_remove_nodo_mapa_destino_maps'),
        ('perfiles', '0004_alter_perfil_nodos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nodos',
            field=models.ManyToManyField(related_name='nodos', to='nodos.nodo'),
        ),
    ]
