# Generated by Django 4.2 on 2024-12-27 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0006_destino_mapa_nodo_mapa'),
        ('hojaderuta', '0012_alter_envio_fecha_alter_envio_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino', to='nodos.nodo'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='hora',
            field=models.TimeField(blank=True, default='23:14:32', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen', to='nodos.nodo'),
        ),
        migrations.AlterField(
            model_name='seguimientodeenvio',
            name='hora_de_modificacion',
            field=models.TimeField(blank=True, default='23:14:32', null=True, verbose_name='Hora de modificacion'),
        ),
    ]
